const catogeryThumb = [
    {
        id: "001",
        image: "images/category-thumb-1.jpg",
        title: "Fruits & Veges",
    },
    {
        id: "002",
        image: "images/category-thumb-2.jpg",
        title: "Bread & Sweets",
    },
    {
        id: "003",
        image: "images/category-thumb-3.jpg",
        title: "Fruits & Veges",
    },
    {
        id: "004",
        image: "images/category-thumb-4.jpg",
        title: "Beverages",
    },
    {
        id: "005",
        image: "images/category-thumb-5.jpg",
        title: "Meat Products",
    },
    {
        id: "006",
        image: "images/category-thumb-6.jpg",
        title: "Leaves",
    },
    {
        id: "007",
        image: "images/category-thumb-7.jpg",
        title: "Fruits & veges",
    },
    {
        id: "008",
        image: "images/category-thumb-8.jpg",
        title: "Breads & Sweets",
    },
]


const productThumb = [
    {
        id: "001",
        image: "images/product-thumb-1.png",
        title: "Whole Wheat Sandwich Bread",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "002",
        image: "images/product-thumb-2.png",
        title: "Whole Grain Oatmeal",
        rating: 41,
        original_Price:54.00,
        current_price:50.00,
        discount_percentage:10,
    },
    {
        id: "003",
        image: "images/product-thumb-3.png",
        title: "Sharp Cheddar Cheese Block",
        rating: 32,
        original_Price:14.00,
        current_price:12.00,
        discount_percentage:10,
    },
    {
        id: "004",
        image: "images/product-thumb-4.png",
        title: "Organic Baby Spinach",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "005",
        image: "images/product-thumb-5.png",
        title: "Organic Spinach Leaves (Fresh Produce)",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "006",
        image: "images/product-thumb-6.png",
        title: "Fresh Salmon",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "007",
        image: "images/product-thumb-7.png",
        title: "Imported Italian Spaghetti Pasta",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "008",
        image: "images/product-thumb-8.png",
        title: "Granny Smith Apples",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "009",
        image: "images/product-thumb-9.png",
        title: "Organic 2% Reduced Fat Milk",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "010",
        image: "images/product-thumb-10.png",
        title: "Greek Style Plain Yogurt",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
]

const featureProduct = [
    {
        id: "001",
        image: "images/product-thumb-10.png",
        title: "Greek Style Plain Yogurt",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "002",
        image: "images/product-thumb-1-2.png",
        title: "Pure Squeezed No Pulp Orange Juice",
        rating: 41,
        original_Price:54.00,
        current_price:50.00,
        discount_percentage:10,
    },
    {
        id: "003",
        image: "images/product-thumb-2-2.png",
        title: "Fresh Oranges",
        rating: 32,
        original_Price:14.00,
        current_price:12.00,
        discount_percentage:10,
    },
    {
        id: "004",
        image: "images/product-thumb-3-2.png",
        title: "Gourmet Dark Chocolate bar",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "005",
        image: "images/product-thumb-4-2.png",
        title: "Fresh Green Celery",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    
]

const popularProduct = [
    {
        id: "001",
        image: "images/product-thumb-5-2.png",
        title: "Sandwich Bread",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "002",
        image: "images/product-thumb-1-3.png",
        title: "Honey Crisp Apple",
        rating: 41,
        original_Price:54.00,
        current_price:50.00,
        discount_percentage:10,
    },
    {
        id: "003",
        image: "images/product-thumb-2-3.png",
        title: "Whole Wheat Sandwich Bread",
        rating: 32,
        original_Price:14.00,
        current_price:12.00,
        discount_percentage:10,
    },
    {
        id: "004",
        image: "images/product-thumb-3-3.png",
        title: "Honey Crisp Apple",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "005",
        image: "images/product-thumb-4-3.png",
        title: "Sunstar Fresh Melon Juice",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    
]


const arriveProduct = [
    {
        id: "001",
        image: "images/product-thumb-5-3.png",
        title: "Sandwich Bread",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "002",
        image: "images/product-thumb-1-4.png",
        title: "Honey Crisp Apple",
        rating: 41,
        original_Price:54.00,
        current_price:50.00,
        discount_percentage:10,
    },
    {
        id: "003",
        image: "images/product-thumb-2-4.png",
        title: "Whole Wheat Sandwich Bread",
        rating: 32,
        original_Price:14.00,
        current_price:12.00,
        discount_percentage:10,
    },
    {
        id: "004",
        image: "images/product-thumb-3-4.png",
        title: "Honey Crisp Apple",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    {
        id: "005",
        image: "images/product-thumb-4-2.png",
        title: "Sunstar Fresh Melon Juice",
        rating: 222,
        original_Price:24.00,
        current_price:18.00,
        discount_percentage:10,
    },
    
]